name: Deploy to Hostinger

on:
  push:
    branches: [gh-pages]

jobs:
  ftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: ./public_html/
          exclude: |
            **/.git*
            **/.github*
            CNAME
